name: Sync with upstream

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'release'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Fetch upstream
        run: git remote add upstream https://github.com/CorentinTh/it-tools.git
      - name: Sync with upstream
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git fetch upstream
          git checkout main
          git rebase upstream/main
          git push
