name: Sync with upstream

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - release
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Fetch upstream
        run: git remote add upstream https://github.com/CorentinTh/it-tools.git
      - name: Sync with upstream
        run: |
          git fetch upstream
          git checkout main
          git rebase upstream/main
          git push
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Git config
        run: |
          git config --global user.name "Jake"
          git config --global user.email "Jake.Laoyu@gmail.com"

      - name: Auto release
        run: |
          git fetch origin
          git checkout release
          git merge main
          git push
          pnpm i --frozen-lockfile
          npx release-it
