name: Sync with upstream

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - release
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Fetch upstream
        run: git remote add upstream https://github.com/CorentinTh/it-tools.git
      - name: Sync with upstream
        run: |
          git fetch upstream
          git checkout main
          git rebase upstream/main
          git push
      - name: Auto release
        run: |
          git checkout release
          git merge main
          git push
          npx release-it
